"""Stub file for custom_components/reflex_silverpoint_react/base.py"""

# ------------------- DO NOT EDIT ----------------------
# This file was generated by `reflex/utils/pyi_generator.py`!
# ------------------------------------------------------
from collections.abc import Mapping, Sequence
from typing import Any, Literal, TypeAlias

import reflex as rx
from reflex_base.event import (
    EventType,
    PointerEventInfo,
)
from reflex_base.vars.base import Var
from reflex_components_core.core.breakpoints import Breakpoints

SILVERPOINT_VERSION = "0.3.0"
SILVERPOINT_LIBRARY = ...
SILVERPOINT_STYLESHEETS = ("@silverpoint/fonts/fonts.css", "@silverpoint/grounds/styles.css")
GroundName: TypeAlias = Literal["silverpoint", "cyanotype"]
Substrate: TypeAlias = Literal["cream", "green", "blue", "ochre", "prussian"]
InkMode: TypeAlias = Literal["ink", "precision"]
Chrome: TypeAlias = Literal["card", "bare"]
HatchFill: TypeAlias = Literal["tile", "per-shape"]
DataTable: TypeAlias = Literal["visible", "hidden", "none"]

class _SilverpointBase(rx.Component):
    def add_imports(self) -> dict[str, list[str]]: ...
    @classmethod
    def create(
        cls,
        *children,
        style: Sequence[Mapping[str, Any]] | Mapping[str, Any] | Var[Mapping[str, Any]] | Breakpoints | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: EventType[()] | None = None,
        on_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_context_menu: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_double_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_focus: EventType[()] | None = None,
        on_mount: EventType[()] | None = None,
        on_mouse_down: EventType[()] | None = None,
        on_mouse_enter: EventType[()] | None = None,
        on_mouse_leave: EventType[()] | None = None,
        on_mouse_move: EventType[()] | None = None,
        on_mouse_out: EventType[()] | None = None,
        on_mouse_over: EventType[()] | None = None,
        on_mouse_up: EventType[()] | None = None,
        on_scroll: EventType[()] | None = None,
        on_scroll_end: EventType[()] | None = None,
        on_unmount: EventType[()] | None = None,
        **props,
    ) -> _SilverpointBase:
        """Create the component.

        Args:
            *children: The children of the component.
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            **props: The props of the component.

        Returns:
            The component."""

class SilverpointChart(_SilverpointBase):
    @classmethod
    def create(
        cls,
        *children,
        data: Var[list[dict[str, Any]]] | list[dict[str, Any]] | None = None,
        ground: Literal["cyanotype", "silverpoint"]
        | Var[Literal["cyanotype", "silverpoint"] | dict[str, Any] | str]
        | dict[str, Any]
        | str
        | None = None,
        substrate: Literal["blue", "cream", "green", "ochre", "prussian"]
        | Var[Literal["blue", "cream", "green", "ochre", "prussian"]]
        | None = None,
        mode: Literal["ink", "precision"] | Var[Literal["ink", "precision"]] | None = None,
        seed: Var[int | str] | int | str | None = None,
        height: Var[float | int] | float | None = None,
        width: Var[float | int] | float | None = None,
        chrome: Literal["bare", "card"] | Var[Literal["bare", "card"]] | None = None,
        hatch_fill: Literal["per-shape", "tile"] | Var[Literal["per-shape", "tile"]] | None = None,
        title: Var[str] | str | None = None,
        badge: Var[str] | str | None = None,
        value: Var[float | int | str] | float | str | None = None,
        unit: Var[str] | str | None = None,
        footer_left: Var[str] | str | None = None,
        footer_right: Var[str] | str | None = None,
        label: Var[str] | str | None = None,
        description: Var[str] | str | None = None,
        data_table: Literal["hidden", "none", "visible"] | Var[Literal["hidden", "none", "visible"]] | None = None,
        locale: Var[str] | str | None = None,
        number_format: Var[dict[str, Any]] | dict[str, Any] | None = None,
        tooltip: Any | Var[Any] | None = None,
        style: Sequence[Mapping[str, Any]] | Mapping[str, Any] | Var[Mapping[str, Any]] | Breakpoints | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_active_change: EventType[Any] | None = None,
        on_blur: EventType[()] | None = None,
        on_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_context_menu: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_double_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_focus: EventType[()] | None = None,
        on_mount: EventType[()] | None = None,
        on_mouse_down: EventType[()] | None = None,
        on_mouse_enter: EventType[()] | None = None,
        on_mouse_leave: EventType[()] | None = None,
        on_mouse_move: EventType[()] | None = None,
        on_mouse_out: EventType[()] | None = None,
        on_mouse_over: EventType[()] | None = None,
        on_mouse_up: EventType[()] | None = None,
        on_scroll: EventType[()] | None = None,
        on_scroll_end: EventType[()] | None = None,
        on_select: EventType[Any] | None = None,
        on_unmount: EventType[()] | None = None,
        **props,
    ) -> SilverpointChart:
        """Create the component.

        Args:
            *children: The children of the component.
            data: no description
            ground: no description
            substrate: no description
            mode: no description
            seed: no description
            height: no description
            width: no description
            chrome: no description
            hatch_fill: no description
            title: no description
            badge: no description
            value: no description
            unit: no description
            footer_left: no description
            footer_right: no description
            label: no description
            description: no description
            data_table: no description
            locale: no description
            number_format: no description
            tooltip: no description
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            on_active_change: no description
            on_select: no description
            **props: The props of the component.

        Returns:
            The component."""

class SilverpointProvider(_SilverpointBase):
    @classmethod
    def create(
        cls,
        *children,
        ground: Literal["cyanotype", "silverpoint"]
        | Var[Literal["cyanotype", "silverpoint"] | dict[str, Any] | str]
        | dict[str, Any]
        | str
        | None = None,
        substrate: Literal["blue", "cream", "green", "ochre", "prussian"]
        | Var[Literal["blue", "cream", "green", "ochre", "prussian"]]
        | None = None,
        mode: Literal["ink", "precision"] | Var[Literal["ink", "precision"]] | None = None,
        locale: Var[str] | str | None = None,
        style: Sequence[Mapping[str, Any]] | Mapping[str, Any] | Var[Mapping[str, Any]] | Breakpoints | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: EventType[()] | None = None,
        on_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_context_menu: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_double_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_focus: EventType[()] | None = None,
        on_mount: EventType[()] | None = None,
        on_mouse_down: EventType[()] | None = None,
        on_mouse_enter: EventType[()] | None = None,
        on_mouse_leave: EventType[()] | None = None,
        on_mouse_move: EventType[()] | None = None,
        on_mouse_out: EventType[()] | None = None,
        on_mouse_over: EventType[()] | None = None,
        on_mouse_up: EventType[()] | None = None,
        on_scroll: EventType[()] | None = None,
        on_scroll_end: EventType[()] | None = None,
        on_unmount: EventType[()] | None = None,
        **props,
    ) -> SilverpointProvider:
        """Create the component.

        Args:
            *children: The children of the component.
            ground: Style ground for every chart below: ``"silverpoint"``, ``"cyanotype"`` or a ground object.
            substrate: Substrate for every chart below.
            mode: Inking mode for every chart below.
            locale: Locale for every chart below.
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            **props: The props of the component.

        Returns:
            The component."""

silverpoint_provider = SilverpointProvider.create
