"""Stub file for custom_components/reflex_silverpoint_react/ui.py"""

# ------------------- DO NOT EDIT ----------------------
# This file was generated by `reflex/utils/pyi_generator.py`!
# ------------------------------------------------------
from collections.abc import Mapping, Sequence
from typing import Any, Literal, TypeAlias

from reflex_base.event import (
    EventType,
    PointerEventInfo,
)
from reflex_base.vars.base import Var
from reflex_components_core.core.breakpoints import Breakpoints

from .dashboard import _SubpathComponent

SILVERPOINT_UI_STYLESHEET = "@silverpoint/grounds/ui.css"
UiSize: TypeAlias = Literal["sm", "md", "lg"]
UiVariant: TypeAlias = Literal["default", "primary", "danger"]
UiOrientation: TypeAlias = Literal["horizontal", "vertical"]
AlertKind: TypeAlias = Literal["info", "success", "warning", "error"]
StepStatus: TypeAlias = Literal["wait", "process", "finish", "error"]
UiToneLevel: TypeAlias = Literal[1, 2, 3, 4]

class SilverpointUi(_SubpathComponent):
    def add_imports(self) -> dict[str, list[str]]: ...
    @classmethod
    def create(
        cls,
        *children,
        ground: Literal["cyanotype", "silverpoint"]
        | Var[Literal["cyanotype", "silverpoint"] | dict[str, Any] | str]
        | dict[str, Any]
        | str
        | None = None,
        substrate: Literal["blue", "cream", "green", "ochre", "prussian"]
        | Var[Literal["blue", "cream", "green", "ochre", "prussian"]]
        | None = None,
        mode: Literal["ink", "precision"] | Var[Literal["ink", "precision"]] | None = None,
        seed: Var[int | str] | int | str | None = None,
        size: Literal["lg", "md", "sm"] | Var[Literal["lg", "md", "sm"]] | None = None,
        style: Sequence[Mapping[str, Any]] | Mapping[str, Any] | Var[Mapping[str, Any]] | Breakpoints | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: EventType[()] | None = None,
        on_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_context_menu: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_double_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_focus: EventType[()] | None = None,
        on_mount: EventType[()] | None = None,
        on_mouse_down: EventType[()] | None = None,
        on_mouse_enter: EventType[()] | None = None,
        on_mouse_leave: EventType[()] | None = None,
        on_mouse_move: EventType[()] | None = None,
        on_mouse_out: EventType[()] | None = None,
        on_mouse_over: EventType[()] | None = None,
        on_mouse_up: EventType[()] | None = None,
        on_scroll: EventType[()] | None = None,
        on_scroll_end: EventType[()] | None = None,
        on_unmount: EventType[()] | None = None,
        **props,
    ) -> SilverpointUi:
        """Create the component.

        Args:
            *children: The children of the component.
            ground: Style ground: ``"silverpoint"`` or ``"cyanotype"``, or a ground object. Defaults to the dashboard's, then the provider's, or ``silverpoint``.
            substrate: Prepared substrate within the ground.
            mode: ``ink`` by default; ``precision`` disables inking.
            seed: Seed of the frame's hand; overrides ``id`` for the frame variant only.
            size: Control size: ``sm``, ``md`` (default) or ``lg``.
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            **props: The props of the component.

        Returns:
            The component."""

class SpButton(SilverpointUi):
    @classmethod
    def create(
        cls,
        *children,
        variant: Literal["danger", "default", "primary"] | Var[Literal["danger", "default", "primary"]] | None = None,
        type: Literal["button", "reset", "submit"] | Var[Literal["button", "reset", "submit"]] | None = None,
        disabled: Var[bool] | bool | None = None,
        label: Var[str] | str | None = None,
        block: Var[bool] | bool | None = None,
        href: Var[str] | str | None = None,
        ground: Literal["cyanotype", "silverpoint"]
        | Var[Literal["cyanotype", "silverpoint"] | dict[str, Any] | str]
        | dict[str, Any]
        | str
        | None = None,
        substrate: Literal["blue", "cream", "green", "ochre", "prussian"]
        | Var[Literal["blue", "cream", "green", "ochre", "prussian"]]
        | None = None,
        mode: Literal["ink", "precision"] | Var[Literal["ink", "precision"]] | None = None,
        seed: Var[int | str] | int | str | None = None,
        size: Literal["lg", "md", "sm"] | Var[Literal["lg", "md", "sm"]] | None = None,
        style: Sequence[Mapping[str, Any]] | Mapping[str, Any] | Var[Mapping[str, Any]] | Breakpoints | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: EventType[()] | None = None,
        on_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_context_menu: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_double_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_focus: EventType[()] | None = None,
        on_mount: EventType[()] | None = None,
        on_mouse_down: EventType[()] | None = None,
        on_mouse_enter: EventType[()] | None = None,
        on_mouse_leave: EventType[()] | None = None,
        on_mouse_move: EventType[()] | None = None,
        on_mouse_out: EventType[()] | None = None,
        on_mouse_over: EventType[()] | None = None,
        on_mouse_up: EventType[()] | None = None,
        on_scroll: EventType[()] | None = None,
        on_scroll_end: EventType[()] | None = None,
        on_unmount: EventType[()] | None = None,
        **props,
    ) -> SpButton:
        """Create the component.

        Args:
            *children: The children of the component.
            variant: ``default``, ``primary`` or ``danger`` (which also draws the exact ✕ glyph).
            type: ``button`` (default), ``submit`` or ``reset``.
            disabled: Not focusable, not submitted; drawn with the disabled tone.
            label: Accessible name of an icon-only button.
            block: Fills the width of its container.
            href: Renders an ``<a>`` to this address.
            ground: Style ground: ``"silverpoint"`` or ``"cyanotype"``, or a ground object. Defaults to the dashboard's, then the provider's, or ``silverpoint``.
            substrate: Prepared substrate within the ground.
            mode: ``ink`` by default; ``precision`` disables inking.
            seed: Seed of the frame's hand; overrides ``id`` for the frame variant only.
            size: Control size: ``sm``, ``md`` (default) or ``lg``.
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            **props: The props of the component.

        Returns:
            The component."""

class SpInput(SilverpointUi):
    @classmethod
    def create(
        cls,
        *children,
        type: Literal["email", "number", "password", "search", "tel", "text", "url"]
        | Var[Literal["email", "number", "password", "search", "tel", "text", "url"]]
        | None = None,
        placeholder: Var[str] | str | None = None,
        name: Var[str] | str | None = None,
        disabled: Var[bool] | bool | None = None,
        read_only: Var[bool] | bool | None = None,
        invalid: Var[bool] | bool | None = None,
        message: Var[str] | str | None = None,
        label: Var[str] | str | None = None,
        value: Var[str] | str | None = None,
        default_value: Var[str] | str | None = None,
        prefix: Component | Var[Component] | None = None,
        suffix: Component | Var[Component] | None = None,
        ground: Literal["cyanotype", "silverpoint"]
        | Var[Literal["cyanotype", "silverpoint"] | dict[str, Any] | str]
        | dict[str, Any]
        | str
        | None = None,
        substrate: Literal["blue", "cream", "green", "ochre", "prussian"]
        | Var[Literal["blue", "cream", "green", "ochre", "prussian"]]
        | None = None,
        mode: Literal["ink", "precision"] | Var[Literal["ink", "precision"]] | None = None,
        seed: Var[int | str] | int | str | None = None,
        size: Literal["lg", "md", "sm"] | Var[Literal["lg", "md", "sm"]] | None = None,
        style: Sequence[Mapping[str, Any]] | Mapping[str, Any] | Var[Mapping[str, Any]] | Breakpoints | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: EventType[()] | None = None,
        on_change: EventType[Any] | None = None,
        on_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_context_menu: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_double_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_focus: EventType[()] | None = None,
        on_mount: EventType[()] | None = None,
        on_mouse_down: EventType[()] | None = None,
        on_mouse_enter: EventType[()] | None = None,
        on_mouse_leave: EventType[()] | None = None,
        on_mouse_move: EventType[()] | None = None,
        on_mouse_out: EventType[()] | None = None,
        on_mouse_over: EventType[()] | None = None,
        on_mouse_up: EventType[()] | None = None,
        on_scroll: EventType[()] | None = None,
        on_scroll_end: EventType[()] | None = None,
        on_unmount: EventType[()] | None = None,
        **props,
    ) -> SpInput:
        """Create the component.

        Args:
            *children: The children of the component.
            type: Native input type: ``text`` (default), ``search``, ``email``, ``url``, ``tel``, ``password``, ``number``.
            placeholder: Hint shown while empty; not a substitute for the accessible name.
            name: Form field name; the native input submits under it.
            disabled: Not focusable and not submitted.
            read_only: Focusable and submitted, but not editable.
            invalid: Sets ``aria-invalid`` and draws the exact ⚠ glyph.
            message: Help or error text under the control, referenced by ``aria-describedby``.
            label: Accessible name, when no ``<label for>`` names the control.
            value: Controlled value.
            default_value: Initial value of an uncontrolled input.
            prefix: Content before the text, inside the box.
            suffix: Content after the text, inside the box.
            ground: Style ground: ``"silverpoint"`` or ``"cyanotype"``, or a ground object. Defaults to the dashboard's, then the provider's, or ``silverpoint``.
            substrate: Prepared substrate within the ground.
            mode: ``ink`` by default; ``precision`` disables inking.
            seed: Seed of the frame's hand; overrides ``id`` for the frame variant only.
            size: Control size: ``sm``, ``md`` (default) or ``lg``.
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            on_change: The new value (a string), not the DOM event.
            **props: The props of the component.

        Returns:
            The component."""

class SpCheckbox(SilverpointUi):
    @classmethod
    def create(
        cls,
        *children,
        label: Var[str] | str | None = None,
        name: Var[str] | str | None = None,
        disabled: Var[bool] | bool | None = None,
        indeterminate: Var[bool] | bool | None = None,
        checked: Var[bool] | bool | None = None,
        default_checked: Var[bool] | bool | None = None,
        ground: Literal["cyanotype", "silverpoint"]
        | Var[Literal["cyanotype", "silverpoint"] | dict[str, Any] | str]
        | dict[str, Any]
        | str
        | None = None,
        substrate: Literal["blue", "cream", "green", "ochre", "prussian"]
        | Var[Literal["blue", "cream", "green", "ochre", "prussian"]]
        | None = None,
        mode: Literal["ink", "precision"] | Var[Literal["ink", "precision"]] | None = None,
        seed: Var[int | str] | int | str | None = None,
        size: Literal["lg", "md", "sm"] | Var[Literal["lg", "md", "sm"]] | None = None,
        style: Sequence[Mapping[str, Any]] | Mapping[str, Any] | Var[Mapping[str, Any]] | Breakpoints | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: EventType[()] | None = None,
        on_change: EventType[Any] | None = None,
        on_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_context_menu: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_double_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_focus: EventType[()] | None = None,
        on_mount: EventType[()] | None = None,
        on_mouse_down: EventType[()] | None = None,
        on_mouse_enter: EventType[()] | None = None,
        on_mouse_leave: EventType[()] | None = None,
        on_mouse_move: EventType[()] | None = None,
        on_mouse_out: EventType[()] | None = None,
        on_mouse_over: EventType[()] | None = None,
        on_mouse_up: EventType[()] | None = None,
        on_scroll: EventType[()] | None = None,
        on_scroll_end: EventType[()] | None = None,
        on_unmount: EventType[()] | None = None,
        **props,
    ) -> SpCheckbox:
        """Create the component.

        Args:
            *children: The children of the component.
            label: The visible text and accessible name. Required.
            name: Form field name; submitted as ``on`` when checked.
            disabled: Not focusable and not submitted.
            indeterminate: Draws the exact dash and sets the native ``indeterminate`` state.
            checked: Controlled state.
            default_checked: Initial state of an uncontrolled checkbox.
            ground: Style ground: ``"silverpoint"`` or ``"cyanotype"``, or a ground object. Defaults to the dashboard's, then the provider's, or ``silverpoint``.
            substrate: Prepared substrate within the ground.
            mode: ``ink`` by default; ``precision`` disables inking.
            seed: Seed of the frame's hand; overrides ``id`` for the frame variant only.
            size: Control size: ``sm``, ``md`` (default) or ``lg``.
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            on_change: The new state (a bool).
            **props: The props of the component.

        Returns:
            The component."""

class SpSwitch(SilverpointUi):
    @classmethod
    def create(
        cls,
        *children,
        label: Var[str] | str | None = None,
        name: Var[str] | str | None = None,
        disabled: Var[bool] | bool | None = None,
        checked: Var[bool] | bool | None = None,
        default_checked: Var[bool] | bool | None = None,
        ground: Literal["cyanotype", "silverpoint"]
        | Var[Literal["cyanotype", "silverpoint"] | dict[str, Any] | str]
        | dict[str, Any]
        | str
        | None = None,
        substrate: Literal["blue", "cream", "green", "ochre", "prussian"]
        | Var[Literal["blue", "cream", "green", "ochre", "prussian"]]
        | None = None,
        mode: Literal["ink", "precision"] | Var[Literal["ink", "precision"]] | None = None,
        seed: Var[int | str] | int | str | None = None,
        size: Literal["lg", "md", "sm"] | Var[Literal["lg", "md", "sm"]] | None = None,
        style: Sequence[Mapping[str, Any]] | Mapping[str, Any] | Var[Mapping[str, Any]] | Breakpoints | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: EventType[()] | None = None,
        on_change: EventType[Any] | None = None,
        on_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_context_menu: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_double_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_focus: EventType[()] | None = None,
        on_mount: EventType[()] | None = None,
        on_mouse_down: EventType[()] | None = None,
        on_mouse_enter: EventType[()] | None = None,
        on_mouse_leave: EventType[()] | None = None,
        on_mouse_move: EventType[()] | None = None,
        on_mouse_out: EventType[()] | None = None,
        on_mouse_over: EventType[()] | None = None,
        on_mouse_up: EventType[()] | None = None,
        on_scroll: EventType[()] | None = None,
        on_scroll_end: EventType[()] | None = None,
        on_unmount: EventType[()] | None = None,
        **props,
    ) -> SpSwitch:
        """Create the component.

        Args:
            *children: The children of the component.
            label: The visible text and accessible name. Required.
            name: Form field name; submitted as ``on`` when on.
            disabled: Not focusable and not submitted.
            checked: Controlled state.
            default_checked: Initial state of an uncontrolled switch.
            ground: Style ground: ``"silverpoint"`` or ``"cyanotype"``, or a ground object. Defaults to the dashboard's, then the provider's, or ``silverpoint``.
            substrate: Prepared substrate within the ground.
            mode: ``ink`` by default; ``precision`` disables inking.
            seed: Seed of the frame's hand; overrides ``id`` for the frame variant only.
            size: Control size: ``sm``, ``md`` (default) or ``lg``.
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            on_change: The new state (a bool).
            **props: The props of the component.

        Returns:
            The component."""

class SpRadioGroup(SilverpointUi):
    @classmethod
    def create(
        cls,
        *children,
        items: Var[list[dict[str, Any]]] | list[dict[str, Any]] | None = None,
        name: Var[str] | str | None = None,
        label: Var[str] | str | None = None,
        orientation: Literal["horizontal", "vertical"] | Var[Literal["horizontal", "vertical"]] | None = None,
        value: Var[str | None] | str | None = None,
        default_value: Var[str | None] | str | None = None,
        ground: Literal["cyanotype", "silverpoint"]
        | Var[Literal["cyanotype", "silverpoint"] | dict[str, Any] | str]
        | dict[str, Any]
        | str
        | None = None,
        substrate: Literal["blue", "cream", "green", "ochre", "prussian"]
        | Var[Literal["blue", "cream", "green", "ochre", "prussian"]]
        | None = None,
        mode: Literal["ink", "precision"] | Var[Literal["ink", "precision"]] | None = None,
        seed: Var[int | str] | int | str | None = None,
        size: Literal["lg", "md", "sm"] | Var[Literal["lg", "md", "sm"]] | None = None,
        style: Sequence[Mapping[str, Any]] | Mapping[str, Any] | Var[Mapping[str, Any]] | Breakpoints | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: EventType[()] | None = None,
        on_change: EventType[Any] | None = None,
        on_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_context_menu: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_double_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_focus: EventType[()] | None = None,
        on_mount: EventType[()] | None = None,
        on_mouse_down: EventType[()] | None = None,
        on_mouse_enter: EventType[()] | None = None,
        on_mouse_leave: EventType[()] | None = None,
        on_mouse_move: EventType[()] | None = None,
        on_mouse_out: EventType[()] | None = None,
        on_mouse_over: EventType[()] | None = None,
        on_mouse_up: EventType[()] | None = None,
        on_scroll: EventType[()] | None = None,
        on_scroll_end: EventType[()] | None = None,
        on_unmount: EventType[()] | None = None,
        **props,
    ) -> SpRadioGroup:
        """Create the component.

        Args:
            *children: The children of the component.
            items: The choices, ``[{key, label, disabled?}]``; build them with :func:`ui_item`. Keys are unique.
            name: Form field name the radios submit under. Required.
            label: The group's name, its ``<legend>``. Required.
            orientation: ``vertical`` (default) or ``horizontal``.
            value: Controlled key; ``None`` checks none.
            default_value: Initial key of an uncontrolled group.
            ground: Style ground: ``"silverpoint"`` or ``"cyanotype"``, or a ground object. Defaults to the dashboard's, then the provider's, or ``silverpoint``.
            substrate: Prepared substrate within the ground.
            mode: ``ink`` by default; ``precision`` disables inking.
            seed: Seed of the frame's hand; overrides ``id`` for the frame variant only.
            size: Control size: ``sm``, ``md`` (default) or ``lg``.
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            on_change: The key checked (a string).
            **props: The props of the component.

        Returns:
            The component."""

class SpSlider(SilverpointUi):
    @classmethod
    def create(
        cls,
        *children,
        label: Var[str] | str | None = None,
        min: Var[float | int] | float | None = None,
        max: Var[float | int] | float | None = None,
        step: Var[float | int] | float | None = None,
        name: Var[str] | str | None = None,
        disabled: Var[bool] | bool | None = None,
        marks: Var[list[float | int]] | list[float | int] | None = None,
        value: Var[float | int] | float | None = None,
        default_value: Var[float | int] | float | None = None,
        ground: Literal["cyanotype", "silverpoint"]
        | Var[Literal["cyanotype", "silverpoint"] | dict[str, Any] | str]
        | dict[str, Any]
        | str
        | None = None,
        substrate: Literal["blue", "cream", "green", "ochre", "prussian"]
        | Var[Literal["blue", "cream", "green", "ochre", "prussian"]]
        | None = None,
        mode: Literal["ink", "precision"] | Var[Literal["ink", "precision"]] | None = None,
        seed: Var[int | str] | int | str | None = None,
        size: Literal["lg", "md", "sm"] | Var[Literal["lg", "md", "sm"]] | None = None,
        style: Sequence[Mapping[str, Any]] | Mapping[str, Any] | Var[Mapping[str, Any]] | Breakpoints | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: EventType[()] | None = None,
        on_change: EventType[Any] | None = None,
        on_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_context_menu: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_double_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_focus: EventType[()] | None = None,
        on_mount: EventType[()] | None = None,
        on_mouse_down: EventType[()] | None = None,
        on_mouse_enter: EventType[()] | None = None,
        on_mouse_leave: EventType[()] | None = None,
        on_mouse_move: EventType[()] | None = None,
        on_mouse_out: EventType[()] | None = None,
        on_mouse_over: EventType[()] | None = None,
        on_mouse_up: EventType[()] | None = None,
        on_scroll: EventType[()] | None = None,
        on_scroll_end: EventType[()] | None = None,
        on_unmount: EventType[()] | None = None,
        **props,
    ) -> SpSlider:
        """Create the component.

        Args:
            *children: The children of the component.
            label: Accessible name of the range. Required.
            min: Lowest value (0 by default).
            max: Highest value (100 by default).
            step: Step (1 by default).
            name: Form field name; the native input submits under it.
            disabled: Not focusable and not submitted.
            marks: Values on the rail that get a labelled mark.
            value: Controlled value.
            default_value: Initial value of an uncontrolled slider (``min`` by default).
            ground: Style ground: ``"silverpoint"`` or ``"cyanotype"``, or a ground object. Defaults to the dashboard's, then the provider's, or ``silverpoint``.
            substrate: Prepared substrate within the ground.
            mode: ``ink`` by default; ``precision`` disables inking.
            seed: Seed of the frame's hand; overrides ``id`` for the frame variant only.
            size: Control size: ``sm``, ``md`` (default) or ``lg``.
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            on_change: The new value (a number).
            **props: The props of the component.

        Returns:
            The component."""

class SpRate(SilverpointUi):
    @classmethod
    def create(
        cls,
        *children,
        label: Var[str] | str | None = None,
        count: Var[int] | int | None = None,
        name: Var[str] | str | None = None,
        disabled: Var[bool] | bool | None = None,
        read_only: Var[bool] | bool | None = None,
        value: Var[int] | int | None = None,
        default_value: Var[int] | int | None = None,
        ground: Literal["cyanotype", "silverpoint"]
        | Var[Literal["cyanotype", "silverpoint"] | dict[str, Any] | str]
        | dict[str, Any]
        | str
        | None = None,
        substrate: Literal["blue", "cream", "green", "ochre", "prussian"]
        | Var[Literal["blue", "cream", "green", "ochre", "prussian"]]
        | None = None,
        mode: Literal["ink", "precision"] | Var[Literal["ink", "precision"]] | None = None,
        seed: Var[int | str] | int | str | None = None,
        size: Literal["lg", "md", "sm"] | Var[Literal["lg", "md", "sm"]] | None = None,
        style: Sequence[Mapping[str, Any]] | Mapping[str, Any] | Var[Mapping[str, Any]] | Breakpoints | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: EventType[()] | None = None,
        on_change: EventType[Any] | None = None,
        on_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_context_menu: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_double_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_focus: EventType[()] | None = None,
        on_mount: EventType[()] | None = None,
        on_mouse_down: EventType[()] | None = None,
        on_mouse_enter: EventType[()] | None = None,
        on_mouse_leave: EventType[()] | None = None,
        on_mouse_move: EventType[()] | None = None,
        on_mouse_out: EventType[()] | None = None,
        on_mouse_over: EventType[()] | None = None,
        on_mouse_up: EventType[()] | None = None,
        on_scroll: EventType[()] | None = None,
        on_scroll_end: EventType[()] | None = None,
        on_unmount: EventType[()] | None = None,
        **props,
    ) -> SpRate:
        """Create the component.

        Args:
            *children: The children of the component.
            label: The group's name, its ``<legend>``. Required.
            count: Number of marks, 1..10 (5 by default).
            name: Form field name; the native radios submit under it.
            disabled: Not focusable and not submitted.
            read_only: Shows the value; the keyboard and the pointer do not change it.
            value: Controlled value.
            default_value: Initial value of an uncontrolled rate (0 by default).
            ground: Style ground: ``"silverpoint"`` or ``"cyanotype"``, or a ground object. Defaults to the dashboard's, then the provider's, or ``silverpoint``.
            substrate: Prepared substrate within the ground.
            mode: ``ink`` by default; ``precision`` disables inking.
            seed: Seed of the frame's hand; overrides ``id`` for the frame variant only.
            size: Control size: ``sm``, ``md`` (default) or ``lg``.
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            on_change: The new value (a number).
            **props: The props of the component.

        Returns:
            The component."""

class SpSegmented(SilverpointUi):
    @classmethod
    def create(
        cls,
        *children,
        items: Var[list[dict[str, Any]]] | list[dict[str, Any]] | None = None,
        label: Var[str] | str | None = None,
        name: Var[str] | str | None = None,
        block: Var[bool] | bool | None = None,
        value: Var[str] | str | None = None,
        default_value: Var[str] | str | None = None,
        ground: Literal["cyanotype", "silverpoint"]
        | Var[Literal["cyanotype", "silverpoint"] | dict[str, Any] | str]
        | dict[str, Any]
        | str
        | None = None,
        substrate: Literal["blue", "cream", "green", "ochre", "prussian"]
        | Var[Literal["blue", "cream", "green", "ochre", "prussian"]]
        | None = None,
        mode: Literal["ink", "precision"] | Var[Literal["ink", "precision"]] | None = None,
        seed: Var[int | str] | int | str | None = None,
        size: Literal["lg", "md", "sm"] | Var[Literal["lg", "md", "sm"]] | None = None,
        style: Sequence[Mapping[str, Any]] | Mapping[str, Any] | Var[Mapping[str, Any]] | Breakpoints | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: EventType[()] | None = None,
        on_change: EventType[Any] | None = None,
        on_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_context_menu: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_double_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_focus: EventType[()] | None = None,
        on_mount: EventType[()] | None = None,
        on_mouse_down: EventType[()] | None = None,
        on_mouse_enter: EventType[()] | None = None,
        on_mouse_leave: EventType[()] | None = None,
        on_mouse_move: EventType[()] | None = None,
        on_mouse_out: EventType[()] | None = None,
        on_mouse_over: EventType[()] | None = None,
        on_mouse_up: EventType[()] | None = None,
        on_scroll: EventType[()] | None = None,
        on_scroll_end: EventType[()] | None = None,
        on_unmount: EventType[()] | None = None,
        **props,
    ) -> SpSegmented:
        """Create the component.

        Args:
            *children: The children of the component.
            items: The options, ``[{key, label, disabled?}]``; build them with :func:`ui_item`.
            label: The control's name, its ``<legend>``. Required.
            name: Form field name; the native radios submit under it.
            block: Fills the width of its container.
            value: Controlled key; an unknown one shows the first enabled segment.
            default_value: Initial key of an uncontrolled control.
            ground: Style ground: ``"silverpoint"`` or ``"cyanotype"``, or a ground object. Defaults to the dashboard's, then the provider's, or ``silverpoint``.
            substrate: Prepared substrate within the ground.
            mode: ``ink`` by default; ``precision`` disables inking.
            seed: Seed of the frame's hand; overrides ``id`` for the frame variant only.
            size: Control size: ``sm``, ``md`` (default) or ``lg``.
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            on_change: The key selected (a string).
            **props: The props of the component.

        Returns:
            The component."""

class SpTabs(SilverpointUi):
    @classmethod
    def create(
        cls,
        *children,
        items: Var[list[dict[str, Any]]] | list[dict[str, Any]] | None = None,
        label: Var[str] | str | None = None,
        orientation: Literal["horizontal", "vertical"] | Var[Literal["horizontal", "vertical"]] | None = None,
        activation: Literal["automatic", "manual"] | Var[Literal["automatic", "manual"]] | None = None,
        value: Var[str] | str | None = None,
        default_value: Var[str] | str | None = None,
        ground: Literal["cyanotype", "silverpoint"]
        | Var[Literal["cyanotype", "silverpoint"] | dict[str, Any] | str]
        | dict[str, Any]
        | str
        | None = None,
        substrate: Literal["blue", "cream", "green", "ochre", "prussian"]
        | Var[Literal["blue", "cream", "green", "ochre", "prussian"]]
        | None = None,
        mode: Literal["ink", "precision"] | Var[Literal["ink", "precision"]] | None = None,
        seed: Var[int | str] | int | str | None = None,
        size: Literal["lg", "md", "sm"] | Var[Literal["lg", "md", "sm"]] | None = None,
        style: Sequence[Mapping[str, Any]] | Mapping[str, Any] | Var[Mapping[str, Any]] | Breakpoints | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: EventType[()] | None = None,
        on_change: EventType[Any] | None = None,
        on_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_context_menu: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_double_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_focus: EventType[()] | None = None,
        on_mount: EventType[()] | None = None,
        on_mouse_down: EventType[()] | None = None,
        on_mouse_enter: EventType[()] | None = None,
        on_mouse_leave: EventType[()] | None = None,
        on_mouse_move: EventType[()] | None = None,
        on_mouse_out: EventType[()] | None = None,
        on_mouse_over: EventType[()] | None = None,
        on_mouse_up: EventType[()] | None = None,
        on_scroll: EventType[()] | None = None,
        on_scroll_end: EventType[()] | None = None,
        on_unmount: EventType[()] | None = None,
        **props,
    ) -> SpTabs:
        """Create the component.

        Args:
            *children: The children of the component.
            items: The tabs, ``[{key, label, disabled?}]``; a disabled one is skipped by the arrows.
            label: Accessible name of the tab list.
            orientation: ``horizontal`` (default) or ``vertical``.
            activation: ``automatic`` (default): a tab is selected as focus reaches it; ``manual``: on Enter or Space.
            value: Controlled key; an unknown one shows the first enabled tab.
            default_value: Initial key of uncontrolled tabs.
            ground: Style ground: ``"silverpoint"`` or ``"cyanotype"``, or a ground object. Defaults to the dashboard's, then the provider's, or ``silverpoint``.
            substrate: Prepared substrate within the ground.
            mode: ``ink`` by default; ``precision`` disables inking.
            seed: Seed of the frame's hand; overrides ``id`` for the frame variant only.
            size: Control size: ``sm``, ``md`` (default) or ``lg``.
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            on_change: The key selected (a string).
            **props: The props of the component.

        Returns:
            The component."""

class SpTabPanel(_SubpathComponent):
    @classmethod
    def create(
        cls,
        *children,
        value: Var[str] | str | None = None,
        style: Sequence[Mapping[str, Any]] | Mapping[str, Any] | Var[Mapping[str, Any]] | Breakpoints | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: EventType[()] | None = None,
        on_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_context_menu: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_double_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_focus: EventType[()] | None = None,
        on_mount: EventType[()] | None = None,
        on_mouse_down: EventType[()] | None = None,
        on_mouse_enter: EventType[()] | None = None,
        on_mouse_leave: EventType[()] | None = None,
        on_mouse_move: EventType[()] | None = None,
        on_mouse_out: EventType[()] | None = None,
        on_mouse_over: EventType[()] | None = None,
        on_mouse_up: EventType[()] | None = None,
        on_scroll: EventType[()] | None = None,
        on_scroll_end: EventType[()] | None = None,
        on_unmount: EventType[()] | None = None,
        **props,
    ) -> SpTabPanel:
        """Create the component.

        Args:
            *children: The children of the component.
            value: The key of the tab that shows this panel. Required.
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            **props: The props of the component.

        Returns:
            The component."""

class SpSteps(SilverpointUi):
    @classmethod
    def create(
        cls,
        *children,
        items: Var[list[dict[str, Any]]] | list[dict[str, Any]] | None = None,
        current: Var[int] | int | None = None,
        orientation: Literal["horizontal", "vertical"] | Var[Literal["horizontal", "vertical"]] | None = None,
        label: Var[str] | str | None = None,
        ground: Literal["cyanotype", "silverpoint"]
        | Var[Literal["cyanotype", "silverpoint"] | dict[str, Any] | str]
        | dict[str, Any]
        | str
        | None = None,
        substrate: Literal["blue", "cream", "green", "ochre", "prussian"]
        | Var[Literal["blue", "cream", "green", "ochre", "prussian"]]
        | None = None,
        mode: Literal["ink", "precision"] | Var[Literal["ink", "precision"]] | None = None,
        seed: Var[int | str] | int | str | None = None,
        size: Literal["lg", "md", "sm"] | Var[Literal["lg", "md", "sm"]] | None = None,
        style: Sequence[Mapping[str, Any]] | Mapping[str, Any] | Var[Mapping[str, Any]] | Breakpoints | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: EventType[()] | None = None,
        on_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_context_menu: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_double_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_focus: EventType[()] | None = None,
        on_mount: EventType[()] | None = None,
        on_mouse_down: EventType[()] | None = None,
        on_mouse_enter: EventType[()] | None = None,
        on_mouse_leave: EventType[()] | None = None,
        on_mouse_move: EventType[()] | None = None,
        on_mouse_out: EventType[()] | None = None,
        on_mouse_over: EventType[()] | None = None,
        on_mouse_up: EventType[()] | None = None,
        on_scroll: EventType[()] | None = None,
        on_scroll_end: EventType[()] | None = None,
        on_unmount: EventType[()] | None = None,
        **props,
    ) -> SpSteps:
        """Create the component.

        Args:
            *children: The children of the component.
            items: The steps, ``[{key, title, description?, status?}]``; build them with :func:`step_item`.
            current: The current step, 0-based. Required.
            orientation: ``horizontal`` (default) or ``vertical``.
            label: Accessible name of the list.
            ground: Style ground: ``"silverpoint"`` or ``"cyanotype"``, or a ground object. Defaults to the dashboard's, then the provider's, or ``silverpoint``.
            substrate: Prepared substrate within the ground.
            mode: ``ink`` by default; ``precision`` disables inking.
            seed: Seed of the frame's hand; overrides ``id`` for the frame variant only.
            size: Control size: ``sm``, ``md`` (default) or ``lg``.
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            **props: The props of the component.

        Returns:
            The component."""

class SpCard(SilverpointUi):
    @classmethod
    def create(
        cls,
        *children,
        title: Var[str] | str | None = None,
        heading_level: Literal[2, 3, 4, 5, 6] | Var[Literal[2, 3, 4, 5, 6]] | None = None,
        extra: Component | Var[Component | str] | str | None = None,
        footer: Component | Var[Component | str] | str | None = None,
        ground: Literal["cyanotype", "silverpoint"]
        | Var[Literal["cyanotype", "silverpoint"] | dict[str, Any] | str]
        | dict[str, Any]
        | str
        | None = None,
        substrate: Literal["blue", "cream", "green", "ochre", "prussian"]
        | Var[Literal["blue", "cream", "green", "ochre", "prussian"]]
        | None = None,
        mode: Literal["ink", "precision"] | Var[Literal["ink", "precision"]] | None = None,
        seed: Var[int | str] | int | str | None = None,
        size: Literal["lg", "md", "sm"] | Var[Literal["lg", "md", "sm"]] | None = None,
        style: Sequence[Mapping[str, Any]] | Mapping[str, Any] | Var[Mapping[str, Any]] | Breakpoints | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: EventType[()] | None = None,
        on_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_context_menu: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_double_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_focus: EventType[()] | None = None,
        on_mount: EventType[()] | None = None,
        on_mouse_down: EventType[()] | None = None,
        on_mouse_enter: EventType[()] | None = None,
        on_mouse_leave: EventType[()] | None = None,
        on_mouse_move: EventType[()] | None = None,
        on_mouse_out: EventType[()] | None = None,
        on_mouse_over: EventType[()] | None = None,
        on_mouse_up: EventType[()] | None = None,
        on_scroll: EventType[()] | None = None,
        on_scroll_end: EventType[()] | None = None,
        on_unmount: EventType[()] | None = None,
        **props,
    ) -> SpCard:
        """Create the component.

        Args:
            *children: The children of the component.
            title: Heading of the card.
            heading_level: Level of the heading, 2 to 6 (3 by default).
            extra: Content at the end of the header, e.g. a period or a tag.
            footer: Content of the footer.
            ground: Style ground: ``"silverpoint"`` or ``"cyanotype"``, or a ground object. Defaults to the dashboard's, then the provider's, or ``silverpoint``.
            substrate: Prepared substrate within the ground.
            mode: ``ink`` by default; ``precision`` disables inking.
            seed: Seed of the frame's hand; overrides ``id`` for the frame variant only.
            size: Control size: ``sm``, ``md`` (default) or ``lg``.
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            **props: The props of the component.

        Returns:
            The component."""

class SpTag(SilverpointUi):
    @classmethod
    def create(
        cls,
        *children,
        tone: Literal[1, 2, 3, 4] | Var[Literal[1, 2, 3, 4]] | None = None,
        closable: Var[bool] | bool | None = None,
        close_label: Var[str] | str | None = None,
        ground: Literal["cyanotype", "silverpoint"]
        | Var[Literal["cyanotype", "silverpoint"] | dict[str, Any] | str]
        | dict[str, Any]
        | str
        | None = None,
        substrate: Literal["blue", "cream", "green", "ochre", "prussian"]
        | Var[Literal["blue", "cream", "green", "ochre", "prussian"]]
        | None = None,
        mode: Literal["ink", "precision"] | Var[Literal["ink", "precision"]] | None = None,
        seed: Var[int | str] | int | str | None = None,
        size: Literal["lg", "md", "sm"] | Var[Literal["lg", "md", "sm"]] | None = None,
        style: Sequence[Mapping[str, Any]] | Mapping[str, Any] | Var[Mapping[str, Any]] | Breakpoints | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: EventType[()] | None = None,
        on_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_close: EventType[()] | None = None,
        on_context_menu: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_double_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_focus: EventType[()] | None = None,
        on_mount: EventType[()] | None = None,
        on_mouse_down: EventType[()] | None = None,
        on_mouse_enter: EventType[()] | None = None,
        on_mouse_leave: EventType[()] | None = None,
        on_mouse_move: EventType[()] | None = None,
        on_mouse_out: EventType[()] | None = None,
        on_mouse_over: EventType[()] | None = None,
        on_mouse_up: EventType[()] | None = None,
        on_scroll: EventType[()] | None = None,
        on_scroll_end: EventType[()] | None = None,
        on_unmount: EventType[()] | None = None,
        **props,
    ) -> SpTag:
        """Create the component.

        Args:
            *children: The children of the component.
            tone: Tonal level 1 to 4 (1 by default).
            closable: Adds a native close button, which fires ``on_close``.
            close_label: Accessible name of the close button (``Remove <text>`` by default).
            ground: Style ground: ``"silverpoint"`` or ``"cyanotype"``, or a ground object. Defaults to the dashboard's, then the provider's, or ``silverpoint``.
            substrate: Prepared substrate within the ground.
            mode: ``ink`` by default; ``precision`` disables inking.
            seed: Seed of the frame's hand; overrides ``id`` for the frame variant only.
            size: Control size: ``sm``, ``md`` (default) or ``lg``.
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            on_close: The close button was clicked.
            **props: The props of the component.

        Returns:
            The component."""

class SpBadge(SilverpointUi):
    @classmethod
    def create(
        cls,
        *children,
        count: Var[int] | int | None = None,
        max: Var[int] | int | None = None,
        dot: Var[bool] | bool | None = None,
        label: Var[str] | str | None = None,
        ground: Literal["cyanotype", "silverpoint"]
        | Var[Literal["cyanotype", "silverpoint"] | dict[str, Any] | str]
        | dict[str, Any]
        | str
        | None = None,
        substrate: Literal["blue", "cream", "green", "ochre", "prussian"]
        | Var[Literal["blue", "cream", "green", "ochre", "prussian"]]
        | None = None,
        mode: Literal["ink", "precision"] | Var[Literal["ink", "precision"]] | None = None,
        seed: Var[int | str] | int | str | None = None,
        size: Literal["lg", "md", "sm"] | Var[Literal["lg", "md", "sm"]] | None = None,
        style: Sequence[Mapping[str, Any]] | Mapping[str, Any] | Var[Mapping[str, Any]] | Breakpoints | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: EventType[()] | None = None,
        on_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_context_menu: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_double_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_focus: EventType[()] | None = None,
        on_mount: EventType[()] | None = None,
        on_mouse_down: EventType[()] | None = None,
        on_mouse_enter: EventType[()] | None = None,
        on_mouse_leave: EventType[()] | None = None,
        on_mouse_move: EventType[()] | None = None,
        on_mouse_out: EventType[()] | None = None,
        on_mouse_over: EventType[()] | None = None,
        on_mouse_up: EventType[()] | None = None,
        on_scroll: EventType[()] | None = None,
        on_scroll_end: EventType[()] | None = None,
        on_unmount: EventType[()] | None = None,
        **props,
    ) -> SpBadge:
        """Create the component.

        Args:
            *children: The children of the component.
            count: The number shown, up to ``max``.
            max: Above it the badge reads ``99+`` (99 by default).
            dot: A dot with no number.
            label: Accessible text of the badge, e.g. ``unread messages``.
            ground: Style ground: ``"silverpoint"`` or ``"cyanotype"``, or a ground object. Defaults to the dashboard's, then the provider's, or ``silverpoint``.
            substrate: Prepared substrate within the ground.
            mode: ``ink`` by default; ``precision`` disables inking.
            seed: Seed of the frame's hand; overrides ``id`` for the frame variant only.
            size: Control size: ``sm``, ``md`` (default) or ``lg``.
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            **props: The props of the component.

        Returns:
            The component."""

class SpDivider(SilverpointUi):
    @classmethod
    def create(
        cls,
        *children,
        orientation: Literal["horizontal", "vertical"] | Var[Literal["horizontal", "vertical"]] | None = None,
        text: Var[str] | str | None = None,
        align: Literal["center", "end", "start"] | Var[Literal["center", "end", "start"]] | None = None,
        ground: Literal["cyanotype", "silverpoint"]
        | Var[Literal["cyanotype", "silverpoint"] | dict[str, Any] | str]
        | dict[str, Any]
        | str
        | None = None,
        substrate: Literal["blue", "cream", "green", "ochre", "prussian"]
        | Var[Literal["blue", "cream", "green", "ochre", "prussian"]]
        | None = None,
        mode: Literal["ink", "precision"] | Var[Literal["ink", "precision"]] | None = None,
        seed: Var[int | str] | int | str | None = None,
        size: Literal["lg", "md", "sm"] | Var[Literal["lg", "md", "sm"]] | None = None,
        style: Sequence[Mapping[str, Any]] | Mapping[str, Any] | Var[Mapping[str, Any]] | Breakpoints | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: EventType[()] | None = None,
        on_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_context_menu: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_double_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_focus: EventType[()] | None = None,
        on_mount: EventType[()] | None = None,
        on_mouse_down: EventType[()] | None = None,
        on_mouse_enter: EventType[()] | None = None,
        on_mouse_leave: EventType[()] | None = None,
        on_mouse_move: EventType[()] | None = None,
        on_mouse_out: EventType[()] | None = None,
        on_mouse_over: EventType[()] | None = None,
        on_mouse_up: EventType[()] | None = None,
        on_scroll: EventType[()] | None = None,
        on_scroll_end: EventType[()] | None = None,
        on_unmount: EventType[()] | None = None,
        **props,
    ) -> SpDivider:
        """Create the component.

        Args:
            *children: The children of the component.
            orientation: ``horizontal`` (default) or ``vertical``.
            text: A caption set in the rule.
            align: Where the caption sits: ``start``, ``center`` (default) or ``end``.
            ground: Style ground: ``"silverpoint"`` or ``"cyanotype"``, or a ground object. Defaults to the dashboard's, then the provider's, or ``silverpoint``.
            substrate: Prepared substrate within the ground.
            mode: ``ink`` by default; ``precision`` disables inking.
            seed: Seed of the frame's hand; overrides ``id`` for the frame variant only.
            size: Control size: ``sm``, ``md`` (default) or ``lg``.
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            **props: The props of the component.

        Returns:
            The component."""

class SpProgress(SilverpointUi):
    @classmethod
    def create(
        cls,
        *children,
        value: Var[float | int] | float | None = None,
        shape: Literal["circle", "line"] | Var[Literal["circle", "line"]] | None = None,
        label: Var[str] | str | None = None,
        show_value: Var[bool] | bool | None = None,
        ground: Literal["cyanotype", "silverpoint"]
        | Var[Literal["cyanotype", "silverpoint"] | dict[str, Any] | str]
        | dict[str, Any]
        | str
        | None = None,
        substrate: Literal["blue", "cream", "green", "ochre", "prussian"]
        | Var[Literal["blue", "cream", "green", "ochre", "prussian"]]
        | None = None,
        mode: Literal["ink", "precision"] | Var[Literal["ink", "precision"]] | None = None,
        seed: Var[int | str] | int | str | None = None,
        size: Literal["lg", "md", "sm"] | Var[Literal["lg", "md", "sm"]] | None = None,
        style: Sequence[Mapping[str, Any]] | Mapping[str, Any] | Var[Mapping[str, Any]] | Breakpoints | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: EventType[()] | None = None,
        on_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_context_menu: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_double_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_focus: EventType[()] | None = None,
        on_mount: EventType[()] | None = None,
        on_mouse_down: EventType[()] | None = None,
        on_mouse_enter: EventType[()] | None = None,
        on_mouse_leave: EventType[()] | None = None,
        on_mouse_move: EventType[()] | None = None,
        on_mouse_out: EventType[()] | None = None,
        on_mouse_over: EventType[()] | None = None,
        on_mouse_up: EventType[()] | None = None,
        on_scroll: EventType[()] | None = None,
        on_scroll_end: EventType[()] | None = None,
        on_unmount: EventType[()] | None = None,
        **props,
    ) -> SpProgress:
        """Create the component.

        Args:
            *children: The children of the component.
            value: 0..100; omitted, the progress is indeterminate.
            shape: ``line`` (default) or ``circle``.
            label: Accessible name. Required.
            show_value: Prints the value (true by default).
            ground: Style ground: ``"silverpoint"`` or ``"cyanotype"``, or a ground object. Defaults to the dashboard's, then the provider's, or ``silverpoint``.
            substrate: Prepared substrate within the ground.
            mode: ``ink`` by default; ``precision`` disables inking.
            seed: Seed of the frame's hand; overrides ``id`` for the frame variant only.
            size: Control size: ``sm``, ``md`` (default) or ``lg``.
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            **props: The props of the component.

        Returns:
            The component."""

class SpAlert(SilverpointUi):
    @classmethod
    def create(
        cls,
        *children,
        kind: Literal["error", "info", "success", "warning"]
        | Var[Literal["error", "info", "success", "warning"]]
        | None = None,
        title: Var[str] | str | None = None,
        closable: Var[bool] | bool | None = None,
        close_label: Var[str] | str | None = None,
        ground: Literal["cyanotype", "silverpoint"]
        | Var[Literal["cyanotype", "silverpoint"] | dict[str, Any] | str]
        | dict[str, Any]
        | str
        | None = None,
        substrate: Literal["blue", "cream", "green", "ochre", "prussian"]
        | Var[Literal["blue", "cream", "green", "ochre", "prussian"]]
        | None = None,
        mode: Literal["ink", "precision"] | Var[Literal["ink", "precision"]] | None = None,
        seed: Var[int | str] | int | str | None = None,
        size: Literal["lg", "md", "sm"] | Var[Literal["lg", "md", "sm"]] | None = None,
        style: Sequence[Mapping[str, Any]] | Mapping[str, Any] | Var[Mapping[str, Any]] | Breakpoints | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: EventType[()] | None = None,
        on_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_close: EventType[()] | None = None,
        on_context_menu: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_double_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_focus: EventType[()] | None = None,
        on_mount: EventType[()] | None = None,
        on_mouse_down: EventType[()] | None = None,
        on_mouse_enter: EventType[()] | None = None,
        on_mouse_leave: EventType[()] | None = None,
        on_mouse_move: EventType[()] | None = None,
        on_mouse_out: EventType[()] | None = None,
        on_mouse_over: EventType[()] | None = None,
        on_mouse_up: EventType[()] | None = None,
        on_scroll: EventType[()] | None = None,
        on_scroll_end: EventType[()] | None = None,
        on_unmount: EventType[()] | None = None,
        **props,
    ) -> SpAlert:
        """Create the component.

        Args:
            *children: The children of the component.
            kind: ``info`` (default), ``success``, ``warning`` or ``error``.
            title: Bold first line of the alert.
            closable: Adds a native close button, which fires ``on_close``.
            close_label: Accessible name of the close button (``Close`` by default).
            ground: Style ground: ``"silverpoint"`` or ``"cyanotype"``, or a ground object. Defaults to the dashboard's, then the provider's, or ``silverpoint``.
            substrate: Prepared substrate within the ground.
            mode: ``ink`` by default; ``precision`` disables inking.
            seed: Seed of the frame's hand; overrides ``id`` for the frame variant only.
            size: Control size: ``sm``, ``md`` (default) or ``lg``.
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            on_close: The close button was clicked.
            **props: The props of the component.

        Returns:
            The component."""

class SpSkeleton(SilverpointUi):
    @classmethod
    def create(
        cls,
        *children,
        lines: Var[int] | int | None = None,
        avatar: Var[bool] | bool | None = None,
        label: Var[str] | str | None = None,
        ground: Literal["cyanotype", "silverpoint"]
        | Var[Literal["cyanotype", "silverpoint"] | dict[str, Any] | str]
        | dict[str, Any]
        | str
        | None = None,
        substrate: Literal["blue", "cream", "green", "ochre", "prussian"]
        | Var[Literal["blue", "cream", "green", "ochre", "prussian"]]
        | None = None,
        mode: Literal["ink", "precision"] | Var[Literal["ink", "precision"]] | None = None,
        seed: Var[int | str] | int | str | None = None,
        size: Literal["lg", "md", "sm"] | Var[Literal["lg", "md", "sm"]] | None = None,
        style: Sequence[Mapping[str, Any]] | Mapping[str, Any] | Var[Mapping[str, Any]] | Breakpoints | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: EventType[()] | None = None,
        on_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_context_menu: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_double_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_focus: EventType[()] | None = None,
        on_mount: EventType[()] | None = None,
        on_mouse_down: EventType[()] | None = None,
        on_mouse_enter: EventType[()] | None = None,
        on_mouse_leave: EventType[()] | None = None,
        on_mouse_move: EventType[()] | None = None,
        on_mouse_out: EventType[()] | None = None,
        on_mouse_over: EventType[()] | None = None,
        on_mouse_up: EventType[()] | None = None,
        on_scroll: EventType[()] | None = None,
        on_scroll_end: EventType[()] | None = None,
        on_unmount: EventType[()] | None = None,
        **props,
    ) -> SpSkeleton:
        """Create the component.

        Args:
            *children: The children of the component.
            lines: Number of lines, 1..8 (3 by default).
            avatar: Draws an avatar placeholder before the lines.
            label: Accessible label (``Loading`` by default).
            ground: Style ground: ``"silverpoint"`` or ``"cyanotype"``, or a ground object. Defaults to the dashboard's, then the provider's, or ``silverpoint``.
            substrate: Prepared substrate within the ground.
            mode: ``ink`` by default; ``precision`` disables inking.
            seed: Seed of the frame's hand; overrides ``id`` for the frame variant only.
            size: Control size: ``sm``, ``md`` (default) or ``lg``.
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            **props: The props of the component.

        Returns:
            The component."""

def ui_item(key: str, label: str, disabled: bool = False) -> dict[str, Any]: ...
def step_item(
    key: str, title: str, description: str | None = None, status: StepStatus | None = None
) -> dict[str, Any]: ...

sp_button = SpButton.create
sp_input = SpInput.create
sp_checkbox = SpCheckbox.create
sp_switch = SpSwitch.create
sp_radio_group = SpRadioGroup.create
sp_slider = SpSlider.create
sp_rate = SpRate.create
sp_segmented = SpSegmented.create
sp_tabs = SpTabs.create
sp_tab_panel = SpTabPanel.create
sp_steps = SpSteps.create
sp_card = SpCard.create
sp_tag = SpTag.create
sp_badge = SpBadge.create
sp_divider = SpDivider.create
sp_progress = SpProgress.create
sp_alert = SpAlert.create
sp_skeleton = SpSkeleton.create
